### ISSUE TITLE
runtime error Failed to Create Swap Chain!

### ISSUE THREAD

**Issue by geotyper** [waxenegger/SdlVulkan#1]
Compile project, remove add models from start, but have runtime error:
sorry this output, without add models:
Created Vulkan Context
Base Directory:
Creating Renderer...
Renderer is Ready
Buffering: 3
Creating Model Pipeline...
Models Reserved Vertex Buffer Size: 250 MB
Models Used Vertex Buffer Size: 0 B
Models Reserved Index Buffer Size: 250 MB
Models Used Index Buffer Size: 0 B
Models Reserved SSBO Buffer Size: 250 MB
Models Used SSBO Buffer Size: 0 B
Added Dummy Texture
Number of Model Textures: 1
Added Model Pipeline
Creating ImGui Pipeline...
Added ImGui Pipeline
Failed to Create Swap Chain!
Destroying Renderer...
Destroying Model Textures...
Destroyed Model Textures
Destroying Logical Device...
Destroyed Renderer
Shutting down Graphics Context...
Shut down Graphics Context

![Screenshot at 2022-05-02 18-33-57](https://user-images.githubusercontent.com/30755433/166262381-6bc16ec6-7f2f-40f1-a44b-dcfdfbed9eb3.png)
Find that it create SwapChain twice,
first time it run without error, second run return false

**Comment by geotyper** [comment]
Created Vulkan Context
Base Directory: 
Creating Renderer...
Renderer is Ready
Buffering: 3
Creating Model Pipeline...
Models Reserved Vertex Buffer Size: 250 MB
Models Used Vertex Buffer Size: 0 B
Models Reserved Index Buffer Size: 250 MB
Models Used Index Buffer Size: 0 B
Models Reserved SSBO Buffer Size: 250 MB
Models Used SSBO Buffer Size: 0 B
Added Dummy Texture
Number of Model Textures: 1
Added Model Pipeline
Creating ImGui Pipeline...
Added ImGui Pipeline
Failed to Create Swap Chain!
Destroying Renderer...
Destroying Model Textures...
Destroyed Model Textures
Destroying Logical Device...
Destroyed Renderer
Shutting down Graphics Context...
Shut down Graphics Context

**Comment by geotyper** [comment]
![Screenshot at 2022-05-02 19-26-31](https://user-images.githubusercontent.com/30755433/166270416-f9b29234-bb95-4f29-8005-202c88ca40df.png)

when you init render, then rub update render where you destroy swapchain and create new one, and then check  return false
![Screenshot at 2022-05-02 19-24-03](https://user-images.githubusercontent.com/30755433/166271285-36991abe-96b4-4616-98e7-ea149ea9eefa.png)

**Comment by waxenegger** [comment]
I should mention, above anything really, that this is a playground ;-)

That said the updateRenderer method is used for various reasons, and, yes, it's correct that in the init the swapchain create method is called twice. That, however, should not be an issue, at least it never was with my setup, because the swapchain is destroyed before recreating it.

If you really want to find out the reason for the failure you need to activate the vulkan validation layer and it should hopefully tell you why things fail in your case. You can do so by uncommenting this line: https://github.com/waxenegger/SdlVulkan/blob/master/src/includes/graphics.h#L55

But, once again, this is more of a hobby, a whole lot of things are suboptimal, a lot of functionality missing still, and the asset loading / rendering is quite specific in what can be changed and what will remain fixed (mixture of read-only device memory buffers and writable ssbo, push constants, etc).
